---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
server:
  port: 8090
eureka:
  instance:
    hostname: peer1
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2:8091/eureka/,http://peer3:8092/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 8091
eureka:
  instance:
    hostname: peer2
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8090/eureka/,http://peer3:8092/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
server:
  port: 8092
eureka:
  instance:
    hostname: peer3
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8090/eureka/,http://peer2:8091/eureka/